name: SecConfigs 

on: [push]

jobs:
  sec-configs:
    runs-on: ubuntu-latest
    continue-on-error: true 
    steps:
     - uses: actions/checkout@v2
     - run: |
        echo "::group::Install Subfinder with go get"
        [ ! -x /home/runner/go/bin/subfinder ] && GO111MODULE=on go get github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
        echo scanme.nmap.org | /home/runner/go/bin/subfinder 
        cp /home/runner/.config/subfinder/config.yaml $GITHUB_WORKSPACE/subfinder.yaml
        echo "downloading amass config from master repo"
        wget https://raw.githubusercontent.com/OWASP/Amass/master/examples/config.ini -O $GITHUB_WORKSPACE/amassconfig.ini
        echo "downloading findomain config from master repo"
        git clone https://github.com/Findomain/Findomain.git $GITHUB_WORKSPACE/findomain
        mkdir $GITHUB_WORKSPACE/findomain-configs
        cp -R $GITHUB_WORKSPACE/findomain/config_examples/* $GITHUB_WORKSPACE/findomain-configs
        sudo rm -r $GITHUB_WORKSPACE/findomain/
        git config --local user.name "node"
        git config --local user.email "node"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git add $GITHUB_WORKSPACE/nuclei.yaml $GITHUB_WORKSPACE/subfinder.yaml $GITHUB_WORKSPACE/naabu.conf
        git commit -am "Configs uploaded"
        git push
